### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by dw-nr-pechanga** [spinscale/elasticsearch-ingest-opennlp#9]
Greetings.

C:\Projects\POC\elasticsearch-ingest-opennlp-master>gradle -v

---
## Gradle 2.13

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Windows 10 10.0 amd64

On Windows 10, tried  gradle clean check and got this...
# C:\Projects\POC\elasticsearch-ingest-opennlp-master>gradle clean check
# Elasticsearch Build Hamster says Hello!

  Gradle Version        : 2.13
  OS Info               : Windows 10 10.0 (amd64)
  JDK Version           : Oracle Corporation 1.8.0_91 [Java HotSpot(TM) 64-Bit Server VM 25.91-b14]
  JAVA_HOME             : C:\Program Files\Java\jdk1.8.0_91\jre
:clean
:compileJava
:processResources UP-TO-DATE
:classes
:copyCheckstyleConf
:checkstyleMain
:copyPluginPropertiesTemplate
:pluginProperties
:compileTestJava
:downloadModels
:processTestResources
:testClasses
:checkstyleTest
:forbiddenApisMain UP-TO-DATE
:forbiddenApisTest UP-TO-DATE
:forbiddenApis UP-TO-DATE
:checkstyle
:dependencyLicenses SKIPPED
:forbiddenPatterns
:jarHell
:licenseHeaders
:loggerUsageCheck
:namingConventions
:thirdPartyAudit SKIPPED
:precommit
:test
==> Test Info: seed=F6E779B710626884; jvms=3; suites=3
Suite: de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests
  2> REPRODUCE WITH: gradle :test -Dtests.seed=F6E779B710626884 -Dtests.class=de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests -Dtests.method="testThatExtractionsWork" -Dtests.security.manager=true -Dtests.locale=tr -Dtests.timezone=Australia/Sydney
ERROR   0.44s J0 | OpenNlpProcessorTests.testThatExtractionsWork <<< FAILURES!

> Throwable #1: java.lang.RuntimeException: resource not found: /models/en-ner-person.bin
>    at __randomizedtesting.SeedInfo.seed([F6E779B710626884:DF89260A7910BF9D]:0)
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:557)
>    at de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests.createOpenNlpService(OpenNlpProcessorTests.java:51)
>    at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:555)
>    ... 37 more
>   2> REPRODUCE WITH: gradle :test -Dtests.seed=F6E779B710626884 -Dtests.class=de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests -Dtests.method="testConstructorNoFieldsSpecified" -Dtests.security.manager=true -Dtests.locale=tr -Dtests.timezone=Australia/Sydney
> ERROR   0.01s J0 | OpenNlpProcessorTests.testConstructorNoFieldsSpecified <<< FAILURES!
> Throwable #1: java.lang.RuntimeException: resource not found: /models/en-ner-person.bin
>    at __randomizedtesting.SeedInfo.seed([F6E779B710626884:C930E1F4AD43259C]:0)
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:557)
>    at de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests.createOpenNlpService(OpenNlpProcessorTests.java:51)
>    at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:555)
>    ... 37 more
>   2> REPRODUCE WITH: gradle :test -Dtests.seed=F6E779B710626884 -Dtests.class=de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests -Dtests.method="testThatFieldsCanBeExcluded" -Dtests.security.manager=true -Dtests.locale=tr -Dtests.timezone=Australia/Sydney
> ERROR   0.03s J0 | OpenNlpProcessorTests.testThatFieldsCanBeExcluded <<< FAILURES!
> Throwable #1: java.lang.RuntimeException: resource not found: /models/en-ner-person.bin
>    at __randomizedtesting.SeedInfo.seed([F6E779B710626884:F2465B72014B4BA2]:0)
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:557)
>    at de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests.createOpenNlpService(OpenNlpProcessorTests.java:51)
>    at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:555)
>    ... 37 more
>   2> REPRODUCE WITH: gradle :test -Dtests.seed=F6E779B710626884 -Dtests.class=de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests -Dtests.method="testThatExistingValuesAreMergedWithoutDuplicates" -Dtests.security.manager=true -Dtests.locale=tr -Dtests.timezone=Australia/Sydney
> ERROR   0.01s J0 | OpenNlpProcessorTests.testThatExistingValuesAreMergedWithoutDuplicates <<< FAILURES!
> Throwable #1: java.lang.RuntimeException: resource not found: /models/en-ner-person.bin
>    at __randomizedtesting.SeedInfo.seed([F6E779B710626884:4754929DF71CCDE8]:0)
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:557)
>    at de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests.createOpenNlpService(OpenNlpProcessorTests.java:51)
>    at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:555)
>    ... 37 more
>   2> NOTE: leaving temporary files on disk at: C:\Projects\POC\elasticsearch-ingest-opennlp-master\build\testrun\test\J0\temp\de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests_F6E779B710626884-001
>   2> NOTE: test params are: codec=Lucene60, sim=ClassicSimilarity, locale=tr, timezone=Australia/Sydney
>   2> NOTE: Windows 10 10.0 amd64/Oracle Corporation 1.8.0_91 (64-bit)/cpus=4,threads=1,free=382928600,total=514850816
>   2> NOTE: All tests run in this JVM: [OpenNlpProcessorTests]
> Completed [1/3] on J0 in 3.28s, 4 tests, 4 errors <<< FAILURES!

Suite: de.spinscale.elasticsearch.ingest.opennlp.OpenNlpServiceTests
  2> REPRODUCE WITH: gradle :test -Dtests.seed=F6E779B710626884 -Dtests.class=de.spinscale.elasticsearch.ingest.opennlp.OpenNlpServiceTests -Dtests.method="testThatModelsCanBeLoaded" -Dtests.security.manager=true -Dtests.locale=vi-VN -Dtests.timezone=Australia/LHI
ERROR   0.41s J1 | OpenNlpServiceTests.testThatModelsCanBeLoaded <<< FAILURES!

> Throwable #1: java.lang.RuntimeException: resource not found: /models/en-ner-person.bin
>    at __randomizedtesting.SeedInfo.seed([F6E779B710626884:2ACAB4F01069CD1E]:0)
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:557)
>    at de.spinscale.elasticsearch.ingest.opennlp.OpenNlpServiceTests.testThatModelsCanBeLoaded(OpenNlpServiceTests.java:43)
>    at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:555)
>    ... 38 more
>   2> NOTE: leaving temporary files on disk at: C:\Projects\POC\elasticsearch-ingest-opennlp-master\build\testrun\test\J1\temp\de.spinscale.elasticsearch.ingest.opennlp.OpenNlpServiceTests_F6E779B710626884-001
>   2> NOTE: test params are: codec=Asserting(Lucene60): {}, docValues:{}, maxPointsInLeafNode=1143, maxMBSortInHeap=7.483929247875422, sim=RandomSimilarity(queryNorm=false,coord=no): {}, locale=vi-VN, timezone=Australia/LHI
>   2> NOTE: Windows 10 10.0 amd64/Oracle Corporation 1.8.0_91 (64-bit)/cpus=4,threads=1,free=385628776,total=514850816
>   2> NOTE: All tests run in this JVM: [OpenNlpServiceTests]
> Completed [2/3] on J1 in 3.27s, 1 test, 1 error <<< FAILURES!

Suite: de.spinscale.elasticsearch.ingest.opennlp.OpenNlpThreadSafeTests
  2> REPRODUCE WITH: gradle :test -Dtests.seed=F6E779B710626884 -Dtests.class=de.spinscale.elasticsearch.ingest.opennlp.OpenNlpThreadSafeTests -Dtests.method="testThatOpenNlpServiceIsThreadSafe" -Dtests.security.manager=true -Dtests.locale=ru-RU -Dtests.timezone=Europe/Amsterdam
ERROR   0.52s J2 | OpenNlpThreadSafeTests.testThatOpenNlpServiceIsThreadSafe <<< FAILURES!

> Throwable #1: java.lang.RuntimeException: resource not found: /models/en-ner-person.bin
>    at __randomizedtesting.SeedInfo.seed([F6E779B710626884:67E9724AE3E1A984]:0)
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:557)
>    at de.spinscale.elasticsearch.ingest.opennlp.OpenNlpThreadSafeTests.setUp(OpenNlpThreadSafeTests.java:47)
>    at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
>    at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:555)
>    ... 37 more
>   2> NOTE: leaving temporary files on disk at: C:\Projects\POC\elasticsearch-ingest-opennlp-master\build\testrun\test\J2\temp\de.spinscale.elasticsearch.ingest.opennlp.OpenNlpThreadSafeTests_F6E779B710626884-001
>   2> NOTE: test params are: codec=Asserting(Lucene60): {}, docValues:{}, maxPointsInLeafNode=1455, maxMBSortInHeap=5.136707662880654, sim=ClassicSimilarity, locale=ru-RU, timezone=Europe/Amsterdam
>   2> NOTE: Windows 10 10.0 amd64/Oracle Corporation 1.8.0_91 (64-bit)/cpus=4,threads=1,free=388316944,total=514850816
>   2> NOTE: All tests run in this JVM: [OpenNlpThreadSafeTests]
> Completed [3/3] on J2 in 3.48s, 1 test, 1 error <<< FAILURES!

Tests with failures:st > Suites [3/3], Tests [006|6|0], in 3.48s J2 completed OpenNlpThreadSafeTests
- de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests.testThatExtractionsWork
- de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests.testConstructorNoFieldsSpecified
- de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests.testThatFieldsCanBeExcluded
- de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests.testThatExistingValuesAreMergedWithoutDuplicates
- de.spinscale.elasticsearch.ingest.opennlp.OpenNlpServiceTests.testThatModelsCanBeLoaded
- de.spinscale.elasticsearch.ingest.opennlp.OpenNlpThreadSafeTests.testThatOpenNlpServiceIsThreadSafe

JUnit4 test failed, ant output was:
   [junit4] <JUnit4> says ???! Master seed: F6E779B710626884
   [junit4] JVM J0:     0.88 ..     5.12 =     4.24s
   [junit4] JVM J1:     0.88 ..     4.92 =     4.03s
   [junit4] JVM J2:     0.88 ..     5.11 =     4.24s
   [junit4] Execution time total: 5.27 sec.
   [junit4] Tests summary: 3 suites, 6 tests, 6 errors

:test FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':test'.
  
  > There were test failures: 3 suites, 6 tests, 6 errors [seed: F6E779B710626884]
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.172 secs

C:\Projects\POC\elasticsearch-ingest-opennlp-master>

**Comment by spinscale** [comment]
I assume that `gradle downloadModels` failed...

I just pushed a fix for OS independent path handling... can you retry after pulling?

**Comment by dw-nr-pechanga** [comment]
Thanks, but still fails.
I ran with --debug and with --stacktrace.
Here are the logs.

David Wong
Esgyn Corporation
(951) 595-7083
david.wong@esgyn.com

**Comment by dw-nr-pechanga** [comment]
[gradle_build.zip](https://github.com/spinscale/elasticsearch-ingest-opennlp/files/435222/gradle_build.zip)

Still fails.
--stacktrace and --debug logs attached.

**Comment by spinscale** [comment]
I had some leftovers in my local installation, which made the tests only work for me. Pushed a fix. Can you retry?

**Comment by dw-nr-pechanga** [comment]
Works now.
Thank you!
